// src/questions.tsx
import { AnyQuestion } from "./types";

export const questions: AnyQuestion[] = [
  // --- PREGUNTAS ORIGINALES (13) ---

  // Razonamiento Fluido (Gf)
  {
    id: 1,
    type: "multiple-choice",
    category: "Razonamiento Fluido",
    text: "Completa la analogía: Guante es a mano como zapato es a...",
    options: ["Pie", "Pierna", "Dedo", "Ropa"],
    answer: "Pie",
    difficulty: 2,
  },
  {
    id: 2,
    type: "multiple-choice",
    category: "Razonamiento Fluido",
    text: "Agua es a tubería como ______ es a cable.",
    options: ["Electricidad", "Luz", "Calor", "Fibra"],
    answer: "Electricidad",
    difficulty: 3,
  },
  {
    id: 3,
    type: "multiple-choice",
    category: "Razonamiento Fluido",
    text: "Si todos los Zips son Zaps y algunos Zaps son Zops, ¿cuál de las siguientes afirmaciones es definitivamente cierta?",
    options: [
      "Todos los Zips son Zops",
      "Algunos Zips son Zops",
      "Ningún Zip es Zop",
      "No se puede determinar",
    ],
    answer: "No se puede determinar",
    difficulty: 6,
  },
  // Comprensión Verbal (Gc)
  {
    id: 4,
    type: "multiple-choice",
    category: "Comprensión Verbal",
    text: '¿Cuál es el significado de la palabra "perspicaz"?',
    options: [
      "Que habla mucho",
      "Que comprende las cosas con agudeza",
      "Que es muy lento",
      "Que es físicamente fuerte",
    ],
    answer: "Que comprende las cosas con agudeza",
    difficulty: 5,
  },
  {
    id: 5,
    type: "multiple-choice",
    category: "Comprensión Verbal",
    text: "¿Cuál es el antónimo de 'locuaz'?",
    options: ["Hablador", "Extrovertido", "Taciturno", "Alegre"],
    answer: "Taciturno",
    difficulty: 7,
  },
  // Memoria de Trabajo (Gsm)
  {
    id: 6,
    type: "multiple-choice",
    category: "Memoria de Trabajo",
    text: "Escribe la secuencia que viste en orden inverso.",
    stimulus: "8 - 4 - 9 - 2 - 7",
    memorizationTime: 8,
    options: ["72948", "84927", "79284", "27498"],
    answer: "72948",
    difficulty: 7,
  },
  {
    id: 7,
    type: "ordering",
    category: "Memoria de Trabajo",
    text: "Ordena la secuencia que viste, primero los números de menor a mayor y luego las letras en orden alfabético.",
    stimulus: "B - 5 - A - 2 - D",
    memorizationTime: 10,
    items: ["B", "5", "A", "2", "D"],
    answer: ["2", "5", "A", "B", "D"],
    difficulty: 6,
  },
  // Conocimiento Cuantitativo (Gq) - CORREGIDO
  {
    id: 8,
    type: "text-input",
    category: "Conocimiento Cuantitativo",
    text: "Calcula mentalmente: (5 * 6) + 12 - 7. Escribe solo el resultado.",
    answer: "35",
    difficulty: 5,
  },
  // Procesamiento Visoespacial (Gv)
  {
    id: 9,
    type: "multiple-choice",
    category: "Procesamiento Visoespacial",
    text: "Si doblas un papel cuadrado por la mitad dos veces y luego cortas una esquina, ¿cuántos agujeros habrá cuando lo desdobles?",
    options: ["1", "2", "3", "4"],
    answer: "4",
    difficulty: 6,
  },
  {
    id: 10,
    type: "text-input",
    category: "Procesamiento Visoespacial",
    text: "Imagina un cubo de 3x3x3. Si pintas todas sus caras exteriores de rojo y luego lo cortas en cubos de 1x1x1, ¿cuántos cubos pequeños no tendrán ninguna cara pintada?",
    answer: "1",
    difficulty: 8,
  },
  // Conocimiento Cuantitativo (Gq)
  {
    id: 11,
    type: "text-input",
    category: "Conocimiento Cuantitativo",
    text: "Un tren viaja a 80 km/h. ¿Cuánto tardará en recorrer 20 km? (Escribe solo el número de minutos)",
    answer: "15",
    difficulty: 4,
  },
  {
    id: 12,
    type: "text-input",
    category: "Conocimiento Cuantitativo",
    text: "Si 5 impresoras tardan 5 minutos en imprimir 5 folletos, ¿cuánto tardaría 1 impresora en imprimir 1 folleto?",
    answer: "5",
    difficulty: 7,
  },
  {
    id: 13,
    type: "multiple-choice",
    category: "Conocimiento Cuantitativo",
    text: "En una clase hay 15 niños y 25 niñas. ¿Qué porcentaje de la clase son niñas?",
    options: ["40%", "60%", "62.5%", "75%"],
    answer: "62.5%",
    difficulty: 5,
  },

  // --- NUEVAS PREGUNTAS (62) ---

  // Razonamiento Fluido (Gf)
  {
    id: 14,
    type: "multiple-choice",
    category: "Razonamiento Fluido",
    text: "¿Qué número sigue en la secuencia: 2, 6, 14, 30, ...?",
    options: ["62", "54", "60", "58"],
    answer: "62",
    difficulty: 7,
  },
  {
    id: 15,
    type: "multiple-choice",
    category: "Razonamiento Fluido",
    text: "Libro es a leer como tenedor es a...",
    options: ["Comer", "Plato", "Cuchillo", "Pinchar"],
    answer: "Comer",
    difficulty: 2,
  },
  {
    id: 16,
    type: "multiple-choice",
    category: "Razonamiento Fluido",
    text: "¿Qué letra continúa la serie: A, C, F, J, O, ...?",
    options: ["T", "U", "V", "S"],
    answer: "U",
    difficulty: 8,
  },
  {
    id: 17,
    type: "multiple-choice",
    category: "Razonamiento Fluido",
    text: "Todas las flores tienen pétalos. Todas las rosas son flores. Por lo tanto...",
    options: [
      "Todas las rosas tienen pétalos",
      "Todos los pétalos son de rosas",
      "Algunas flores no son rosas",
      "Ninguna de las anteriores",
    ],
    answer: "Todas las rosas tienen pétalos",
    difficulty: 5,
  },
  {
    id: 18,
    type: "text-input",
    category: "Razonamiento Fluido",
    text: "Descubre el patrón y completa la serie: 4, 9, 16, 25, ...",
    answer: "36",
    difficulty: 4,
  },
  {
    id: 19,
    type: "multiple-choice",
    category: "Razonamiento Fluido",
    text: "Si reorganizas las letras 'R A P S I', obtendrías el nombre de una ciudad. ¿Cuál?",
    options: ["París", "Praga", "Roma", "Sofía"],
    answer: "París",
    difficulty: 6,
  },
  {
    id: 20,
    type: "multiple-choice",
    category: "Razonamiento Fluido",
    text: "Ojo es a ver como oído es a...",
    options: ["Escuchar", "Sonido", "Oreja", "Ruido"],
    answer: "Escuchar",
    difficulty: 2,
  },
  {
    id: 21,
    type: "text-input",
    category: "Razonamiento Fluido",
    text: "¿Qué número falta en la serie: 8, 27, 64, 125, ...?",
    answer: "216",
    difficulty: 9,
  },
  {
    id: 22,
    type: "multiple-choice",
    category: "Razonamiento Fluido",
    text: "Un caracol está en el fondo de un pozo de 10 metros. Cada día sube 3 metros y cada noche resbala 2 metros. ¿Cuántos días tardará en salir del pozo?",
    options: ["10 días", "9 días", "8 días", "7 días"],
    answer: "8 días",
    difficulty: 8,
  },
  {
    id: 23,
    type: "multiple-choice",
    category: "Razonamiento Fluido",
    text: "El hermano de Juan tiene una hermana. Esa hermana tiene el doble de hermanos que de hermanas. ¿Cuántos hermanos y hermanas hay en la familia?",
    options: [
      "4 hermanos y 3 hermanas",
      "3 hermanos y 2 hermanas",
      "2 hermanos y 1 hermana",
      "5 hermanos y 2 hermanas",
    ],
    answer: "4 hermanos y 3 hermanas",
    difficulty: 10,
  },
  {
    id: 24,
    type: "multiple-choice",
    category: "Razonamiento Fluido",
    text: "Si A es el padre de B, pero B no es el hijo de A, ¿qué relación tienen?",
    options: [
      "A es el tío de B",
      "B es la hija de A",
      "B es el sobrino de A",
      "No es posible",
    ],
    answer: "B es la hija de A",
    difficulty: 4,
  },
  {
    id: 25,
    type: "text-input",
    category: "Razonamiento Fluido",
    text: "Completa la serie: 1, 1, 2, 3, 5, 8, 13, ...",
    answer: "21",
    difficulty: 7,
  },

  // Comprensión Verbal (Gc)
  {
    id: 26,
    type: "multiple-choice",
    category: "Comprensión Verbal",
    text: "¿Qué significa 'efímero'?",
    options: [
      "Que dura mucho tiempo",
      "Que es de poca duración",
      "Que es muy brillante",
      "Que es invisible",
    ],
    answer: "Que es de poca duración",
    difficulty: 6,
  },
  {
    id: 27,
    type: "multiple-choice",
    category: "Comprensión Verbal",
    text: "Elige el sinónimo de 'ubérrimo'.",
    options: ["Pobre", "Escaso", "Abundante", "Triste"],
    answer: "Abundante",
    difficulty: 9,
  },
  {
    id: 28,
    type: "multiple-choice",
    category: "Comprensión Verbal",
    text: "El refrán 'A buen entendedor, pocas palabras bastan' significa:",
    options: [
      "Es mejor no hablar mucho",
      "Las personas inteligentes no necesitan largas explicaciones",
      "Hablar poco es de sabios",
      "Hay que ser breve para que te entiendan",
    ],
    answer: "Las personas inteligentes no necesitan largas explicaciones",
    difficulty: 5,
  },
  {
    id: 29,
    type: "multiple-choice",
    category: "Comprensión Verbal",
    text: "Identifica la palabra que no pertenece al grupo.",
    options: ["Coche", "Avión", "Barco", "Bicicleta"],
    answer: "Bicicleta",
    difficulty: 4,
  },
  {
    id: 30,
    type: "multiple-choice",
    category: "Comprensión Verbal",
    text: "¿Cuál es el antónimo de 'esotérico'?",
    options: ["Misterioso", "Oculto", "Público", "Complejo"],
    answer: "Público",
    difficulty: 8,
  },
  {
    id: 31,
    type: "multiple-choice",
    category: "Comprensión Verbal",
    text: "¿Qué palabra se define como 'aversión o rechazo hacia los extranjeros'?",
    options: ["Agorafobia", "Claustrofobia", "Xenofobia", "Glosofobia"],
    answer: "Xenofobia",
    difficulty: 7,
  },
  {
    id: 32,
    type: "multiple-choice",
    category: "Comprensión Verbal",
    text: "Un 'oxímoron' es:",
    options: [
      "Una figura retórica que usa dos conceptos de significado opuesto",
      "Una exageración evidente",
      "Una pregunta que no espera respuesta",
      "Una comparación entre dos cosas",
    ],
    answer: "Una figura retórica que usa dos conceptos de significado opuesto",
    difficulty: 8,
  },
  {
    id: 33,
    type: "multiple-choice",
    category: "Comprensión Verbal",
    text: "Elige el antónimo de 'parco'.",
    options: ["Hablador", "Tacaño", "Abundante", "Feliz"],
    answer: "Hablador",
    difficulty: 6,
  },
  {
    id: 34,
    type: "multiple-choice",
    category: "Comprensión Verbal",
    text: "¿Qué significa el término 'falacia ad hominem'?",
    options: [
      "Apelar a la popularidad",
      "Atacar a la persona en lugar de su argumento",
      "Asumir que algo es verdad porque no se ha probado que es falso",
      "Una conclusión que no se sigue de las premisas",
    ],
    answer: "Atacar a la persona en lugar de su argumento",
    difficulty: 9,
  },
  {
    id: 35,
    type: "multiple-choice",
    category: "Comprensión Verbal",
    text: "Elige un sinónimo de 'inefable'.",
    options: ["Inepto", "Indecible", "Inevitable", "Inexorable"],
    answer: "Indecible",
    difficulty: 10,
  },
  {
    id: 36,
    type: "multiple-choice",
    category: "Comprensión Verbal",
    text: "La palabra 'resiliencia' se refiere a:",
    options: [
      "La capacidad de resistir la presión",
      "La capacidad de adaptarse y superar la adversidad",
      "La fragilidad de un material",
      "La memoria a largo plazo",
    ],
    answer: "La capacidad de adaptarse y superar la adversidad",
    difficulty: 6,
  },
  {
    id: 37,
    type: "multiple-choice",
    category: "Comprensión Verbal",
    text: "Elige la palabra que completa mejor la frase: Su discurso fue tan ______ que todos se durmieron.",
    options: ["lacónico", "somnífero", "elocuente", "conciso"],
    answer: "somnífero",
    difficulty: 5,
  },
  {
    id: 38,
    type: "multiple-choice",
    category: "Comprensión Verbal",
    text: "¿Cuál de estas palabras es un 'palíndromo'?",
    options: ["Radar", "Casa", "Sol", "Amigo"],
    answer: "Radar",
    difficulty: 4,
  },

  // Memoria de Trabajo (Gsm)
  {
    id: 39,
    type: "text-input",
    category: "Memoria de Trabajo",
    text: "Tras ver la secuencia, cuenta cuántas veces aparece el número 5 y escribe el total.",
    stimulus: "5 8 2 5 9 1 5 3 4 5",
    memorizationTime: 10,
    answer: "4",
    difficulty: 6,
  },
  {
    id: 41,
    type: "ordering",
    category: "Memoria de Trabajo",
    text: "Ordena alfabéticamente las palabras que viste.",
    stimulus: "Cebra, Barco, Avión, Dedo, Gato",
    memorizationTime: 8,
    items: ["Cebra", "Barco", "Avión", "Dedo", "Gato"],
    answer: ["Avión", "Barco", "Cebra", "Dedo", "Gato"],
    difficulty: 5,
  },
  {
    id: 42,
    type: "multiple-choice",
    category: "Memoria de Trabajo",
    text: "Escribe la secuencia de números que viste en orden inverso.",
    stimulus: "3-1-4-1-5-9",
    memorizationTime: 8,
    options: ["951413", "314159", "915143", "315419"],
    answer: "951413",
    difficulty: 8,
  },
  {
    id: 43,
    type: "multiple-choice",
    category: "Memoria de Trabajo",
    text: "Aplica la regla que viste a la secuencia y escribe el resultado sin espacios.",
    stimulus:
      "Secuencia: 2, 7, 4, 9, 6. Regla: Suma 3 a los pares, resta 1 a los impares.",
    memorizationTime: 15,
    options: ["56789", "57689", "56798", "65789"],
    answer: "56789",
    difficulty: 9,
  },
  {
    id: 44,
    type: "ordering",
    category: "Memoria de Trabajo",
    text: "Ordena los siguientes eventos históricos cronológicamente (del más antiguo al más reciente).",
    items: [
      "Caída del Imperio Romano",
      "Descubrimiento de América",
      "Revolución Francesa",
      "Invención de la imprenta",
    ],
    answer: [
      "Caída del Imperio Romano",
      "Invención de la imprenta",
      "Descubrimiento de América",
      "Revolución Francesa",
    ],
    difficulty: 7,
  },
  {
    id: 46,
    type: "multiple-choice",
    category: "Memoria de Trabajo",
    text: "Escribe la segunda letra de la segunda palabra de la lista que memorizaste.",
    stimulus: "Manzana, Plátano, Cereza",
    memorizationTime: 7,
    options: ["a", "l", "á", "p"],
    answer: "l",
    difficulty: 6,
  },
  {
    id: 48,
    type: "ordering",
    category: "Memoria de Trabajo",
    text: "Ordena estas capitales por la población de sus países (de mayor a menor).",
    items: ["Tokio", "Madrid", "Pekín", "Washington D.C."],
    answer: ["Pekín", "Washington D.C.", "Tokio", "Madrid"],
    difficulty: 10,
  },
  {
    id: 50,
    type: "multiple-choice",
    category: "Memoria de Trabajo",
    text: "Elige la opción con los números primos que viste en orden descendente.",
    stimulus: "11, 13, 17, 19, 23, 29",
    memorizationTime: 12,
    options: [
      "29,23,19,17,13,11",
      "30,25,20,15,10",
      "29,27,23,19,17,11",
      "29,23,19,15,13,11",
    ],
    answer: "29,23,19,17,13,11",
    difficulty: 8,
  },

  // Conocimiento Cuantitativo (Gq) - PREGUNTAS RECLASIFICADAS
  {
    id: 40,
    type: "text-input",
    category: "Conocimiento Cuantitativo",
    text: "Calcula mentalmente: 15 * 3 + 20 / 4 - 10. Escribe el resultado.",
    answer: "40",
    difficulty: 8,
  },
  {
    id: 45,
    type: "text-input",
    category: "Conocimiento Cuantitativo",
    text: "Calcula mentalmente: (12 + 8) / 4 * (10 - 3). Escribe solo el resultado.",
    answer: "35",
    difficulty: 7,
  },
  {
    id: 47,
    type: "multiple-choice",
    category: "Conocimiento Cuantitativo",
    text: "Elige la opción que contiene los meses del año con 30 días, ordenados alfabéticamente.",
    options: [
      "abril, junio, noviembre, septiembre",
      "abril, junio, septiembre, noviembre",
      "abril, mayo, junio, septiembre",
      "febrero, abril, junio, noviembre",
    ],
    answer: "abril, junio, septiembre, noviembre",
    difficulty: 8,
  },
  {
    id: 49,
    type: "multiple-choice",
    category: "Conocimiento Cuantitativo",
    text: "Si hoy es sábado, ¿qué día será en 23 días?",
    options: ["domingo", "lunes", "martes", "miércoles"],
    answer: "lunes",
    difficulty: 5,
  },

  // Procesamiento Visoespacial (Gv)
  {
    id: 51,
    type: "multiple-choice",
    category: "Procesamiento Visoespacial",
    text: "¿Qué figura se obtiene si rotas la letra 'p' 180 grados?",
    options: ["b", "d", "q", "p"],
    answer: "d",
    difficulty: 5,
  },
  {
    id: 52,
    type: "multiple-choice",
    category: "Procesamiento Visoespacial",
    text: "Un coche viaja 10 km al norte, 10 km al este y 10 km al sur. ¿A qué distancia está del punto de partida?",
    options: ["30 km", "10 km", "0 km", "20 km"],
    answer: "10 km",
    difficulty: 6,
  },
  {
    id: 53,
    type: "text-input",
    category: "Procesamiento Visoespacial",
    text: "Imagina un cubo de 4x4x4 hecho de cubitos de 1x1x1. ¿Cuántos cubitos tocan al menos una de las caras exteriores?",
    answer: "56",
    difficulty: 9,
  },
  {
    id: 54,
    type: "multiple-choice",
    category: "Procesamiento Visoespacial",
    text: "Si miras un reloj a las 3:15, ¿cuál es el ángulo agudo entre las manecillas de la hora y el minutero?",
    options: ["0 grados", "15 grados", "7.5 grados", "10 grados"],
    answer: "7.5 grados",
    difficulty: 8,
  },
  {
    id: 55,
    type: "multiple-choice",
    category: "Procesamiento Visoespacial",
    text: "¿Cuál de estas figuras no se puede dibujar sin levantar el lápiz del papel ni pasar dos veces por la misma línea?",
    image: "https://i.imgur.com/2yQfC2a.png",
    options: [
      "Un cuadrado con sus dos diagonales",
      "Una estrella de cinco puntas",
      "Un sobre cerrado",
      "Una casa con una X dentro",
    ],
    answer: "Una casa con una X dentro",
    difficulty: 9,
  },
  {
    id: 56,
    type: "multiple-choice",
    category: "Procesamiento Visoespacial",
    text: "Estás en una habitación sin ventanas con 3 interruptores fuera que controlan 3 bombillas dentro. Puedes entrar a la habitación solo una vez. ¿Cómo sabes qué interruptor corresponde a cada bombilla?",
    options: [
      "Encender un interruptor, esperar, apagarlo. Encender otro y entrar.",
      "Encender dos interruptores y entrar.",
      "Encender un interruptor y entrar rápidamente.",
      "Es imposible saberlo.",
    ],
    answer:
      "Encender un interruptor, esperar, apagarlo. Encender otro y entrar.",
    difficulty: 10,
  },
  {
    id: 57,
    type: "multiple-choice",
    category: "Procesamiento Visoespacial",
    text: "Un mapa está orientado con el Norte hacia arriba. Si caminas 5 km al Sur, luego 5 km al Oeste y luego 5 km al Norte, ¿en qué dirección está tu punto de partida?",
    options: ["Norte", "Sur", "Este", "Oeste"],
    answer: "Este",
    difficulty: 5,
  },
  {
    id: 58,
    type: "text-input",
    category: "Procesamiento Visoespacial",
    text: "¿Cuántos cuadrados en total hay en un tablero de ajedrez de 8x8?",
    answer: "204",
    difficulty: 8,
  },
  {
    id: 59,
    type: "multiple-choice",
    category: "Procesamiento Visoespacial",
    text: "Si desdoblas un cubo, ¿cuál de las siguientes formas NO puede ser su desarrollo plano?",
    options: [
      "Una cruz de 6 cuadrados",
      "Una línea de 6 cuadrados",
      "Un bloque de 2x3 cuadrados",
      "Un cuadrado de 3x3 con un cuadrado faltante en el medio",
    ],
    answer: "Un cuadrado de 3x3 con un cuadrado faltante en el medio",
    difficulty: 7,
  },
  {
    id: 60,
    type: "multiple-choice",
    category: "Procesamiento Visoespacial",
    text: "Si un avión se estrella justo en la frontera entre Argentina y Chile, ¿dónde se entierra a los supervivientes?",
    options: [
      "En Argentina",
      "En Chile",
      "En el país de su nacionalidad",
      "No se les entierra",
    ],
    answer: "No se les entierra",
    difficulty: 6,
  },
  {
    id: 61,
    type: "multiple-choice",
    category: "Procesamiento Visoespacial",
    text: "En una carrera, adelantas al segundo. ¿En qué posición quedas?",
    options: ["primero", "segundo", "tercero", "último"],
    answer: "segundo",
    difficulty: 3,
  },
  {
    id: 62,
    type: "multiple-choice",
    category: "Procesamiento Visoespacial",
    text: "Imagina que estás mirando un espejo. Levantas tu mano izquierda. ¿Qué mano levanta tu reflejo?",
    options: ["La izquierda", "La derecha", "Ambas", "Ninguna"],
    answer: "La izquierda",
    difficulty: 7,
  },
  {
    id: 63,
    type: "text-input",
    category: "Procesamiento Visoespacial",
    text: "Un granjero tiene 17 ovejas. Todas mueren menos nueve. ¿Cuántas le quedan?",
    answer: "9",
    difficulty: 4,
  },

  // Conocimiento Cuantitativo (Gq)
  {
    id: 64,
    type: "multiple-choice",
    category: "Conocimiento Cuantitativo",
    text: "El precio de un artículo se incrementa un 20% y luego se reduce un 20%. ¿Cuál es el cambio porcentual neto?",
    options: ["-4%", "0%", "4%", "-2%"],
    answer: "-4%",
    difficulty: 8,
  },
  {
    id: 65,
    type: "text-input",
    category: "Conocimiento Cuantitativo",
    text: "Si 3 gatos pueden atrapar 3 ratones en 3 minutos, ¿cuánto tiempo necesitarán 100 gatos para atrapar 100 ratones?",
    answer: "3",
    difficulty: 7,
  },
  {
    id: 66,
    type: "multiple-choice",
    category: "Conocimiento Cuantitativo",
    text: "Un bate y una pelota cuestan $1.10 en total. El bate cuesta $1.00 más que la pelota. ¿Cuánto cuesta la pelota?",
    options: ["$0.10", "$0.05", "$1.00", "$0.15"],
    answer: "$0.05",
    difficulty: 8,
  },
  {
    id: 67,
    type: "text-input",
    category: "Conocimiento Cuantitativo",
    text: "En un lago, hay un parche de nenúfares. Cada día, el parche duplica su tamaño. Si tarda 48 días en cubrir todo el lago, ¿cuántos días tarda en cubrir la mitad?",
    answer: "47",
    difficulty: 7,
  },
  {
    id: 68,
    type: "text-input",
    category: "Conocimiento Cuantitativo",
    text: "¿Cuál es el siguiente número primo después de 43?",
    answer: "47",
    difficulty: 5,
  },
  {
    id: 69,
    type: "multiple-choice",
    category: "Conocimiento Cuantitativo",
    text: "Tienes dos cuerdas que tardan exactamente 1 hora en quemarse cada una, pero no se queman a un ritmo uniforme. ¿Cómo medirías 45 minutos?",
    options: [
      "Quemas una por un extremo y la otra por el otro",
      "Quemas una por ambos extremos y la otra por uno",
      "Cortas una por la mitad",
      "No es posible",
    ],
    answer: "Quemas una por ambos extremos y la otra por uno",
    difficulty: 10,
  },
  {
    id: 70,
    type: "text-input",
    category: "Conocimiento Cuantitativo",
    text: "Un padre tiene 48 años y su hijo 22. ¿Hace cuántos años la edad del padre era el triple que la del hijo?",
    answer: "9",
    difficulty: 8,
  },
  {
    id: 71,
    type: "text-input",
    category: "Conocimiento Cuantitativo",
    text: "Si se necesitan 8 hombres para construir una pared en 10 horas, ¿cuántas horas necesitarían 5 hombres para construir la misma pared?",
    answer: "16",
    difficulty: 6,
  },
  {
    id: 72,
    type: "multiple-choice",
    category: "Conocimiento Cuantitativo",
    text: "Tienes 3 cajas cerradas. Una contiene solo manzanas, otra solo naranjas, y la tercera manzanas y naranjas. Todas están mal etiquetadas. Sacando una sola fruta de una sola caja, ¿cómo puedes etiquetarlas todas correctamente?",
    options: [
      "Sacas de la caja 'naranjas'",
      "Sacas de la caja 'manzanas'",
      "Sacas de la caja 'manzanas y naranjas'",
      "Es imposible",
    ],
    answer: "Sacas de la caja 'manzanas y naranjas'",
    difficulty: 9,
  },
  {
    id: 73,
    type: "text-input",
    category: "Conocimiento Cuantitativo",
    text: "Encuentra el valor de X: 3, 7, 15, 31, 63, X",
    answer: "127",
    difficulty: 7,
  },
  {
    id: 74,
    type: "multiple-choice",
    category: "Conocimiento Cuantitativo",
    text: "Hay 8 bolas idénticas en apariencia, pero una es ligeramente más pesada. Usando una balanza de dos platos, ¿cuál es el número mínimo de pesadas para encontrar la bola pesada?",
    options: ["1", "2", "3", "4"],
    answer: "2",
    difficulty: 9,
  },
  {
    id: 75,
    type: "multiple-choice", // CORREGIDO
    category: "Conocimiento Cuantitativo",
    text: "El abuelo de María tiene 5 hijos. Uno de ellos es el padre de María. Cada uno de los 5 hijos tiene 3 hijos. ¿Cuántos primos tiene María?",
    options: ["15", "14", "12", "9"],
    answer: "12",
    difficulty: 8,
  },
];
